.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. unitedcontinentaldollar_qt test_unitedcontinentaldollar_qt
clean: FORCE
	$(MAKE) -C .. unitedcontinentaldollar_qt_clean test_unitedcontinentaldollar_qt_clean
check: FORCE
	$(MAKE) -C .. test_unitedcontinentaldollar_qt_check
unitedcontinentaldollar-qt unitedcontinentaldollar-qt.exe: FORCE
	 $(MAKE) -C .. unitedcontinentaldollar_qt
